name: Java CI/CD with DevSecOps

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app-code/**'
      - '.github/workflows/**'

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/devops-java-app
  IMAGE_TAG: v1.0.${{ github.run_number }}
  WORKING_DIR: ./app-code

jobs:
  build-and-secure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: './app-code/pom.xml'

    - name: Run Unit Tests
      run: |
        cd ${{ env.WORKING_DIR }}
        mvn test

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/maven@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --file=app-code/pom.xml --severity-threshold=high 
      continue-on-error: true

    - name: Build with Maven
      run: |
        cd ${{ env.WORKING_DIR }}
        mvn clean package -DskipTests

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        cd ${{ env.WORKING_DIR }}
        docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
        docker tag ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.DOCKER_IMAGE_NAME }}:latest

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Push Docker Image
      run: |
        docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        docker push ${{ env.DOCKER_IMAGE_NAME }}:latest